/**
 * These are drawn from the activities_activitytype table in the database
 * I've excluded activities that involve restaurants, breweries, wineries, etc.
 */
const wellnessActivityTypes = [
  { id: 13, name: "Hikes" },
  { id: 120, name: "Walk" },
  { id: 21, name: "Museums" },
  { id: 152, name: "Museum" },
  { id: 174, name: "History Museum" },
  { id: 211, name: "Science Museum" },
  { id: 231, name: "Art Museum" }
];

const allActivityTypes = [
  { id: 1, name: "Bike Trails" },
  { id: 2, name: "Indoor Activities" },
  { id: 4, name: "Playground" },
  { id: 5, name: "Water Activities" },
  { id: 6, name: "Run" },
  { id: 8, name: "Local Highlights" },
  { id: 9, name: "Seasonal Activities" },
  { id: 10, name: "Road Trips" },
  { id: 11, name: "Camping" },
  { id: 13, name: "Hikes" },
  { id: 18, name: "Outdoor Adventures" },
  { id: 19, name: "Horseback Rides" },
  { id: 20, name: "Fun Paid Activities" },
  { id: 21, name: "Museums" },
  { id: 58, name: "Parks" },
  { id: 87, name: "Breweries & Wineries" },
  { id: 88, name: "Farms & Orchards" },
  { id: 89, name: "Restaurants" },
  { id: 91, name: "Swim" },
  { id: 120, name: "Walk" },
  { id: 121, name: "Ski & Board" },
  { id: 122, name: "Yoga" },
  { id: 123, name: "Surf" },
  { id: 124, name: "Ice Skate" },
  { id: 125, name: "Basketball" },
  { id: 126, name: "Tennis" },
  { id: 127, name: "Golf" },
  { id: 128, name: "Baseball" },
  { id: 129, name: "Soccer" },
  { id: 130, name: "Volleyball" },
  { id: 131, name: "Paddle" },
  { id: 132, name: "Picnic" },
  { id: 133, name: "Amusement Parks" },
  { id: 134, name: "Play Places" },
  { id: 135, name: "Boating" },
  { id: 136, name: "Gardens" },
  { id: 137, name: "Scenic Drive" },
  { id: 138, name: "Library" },
  { id: 139, name: "Historic Destination" },
  { id: 140, name: "Aquarium" },
  { id: 141, name: "Zoo" },
  { id: 142, name: "Nature Center" },
  { id: 143, name: "Ice Cream" },
  { id: 144, name: "Cafe" },
  { id: 145, name: "Bakery" },
  { id: 146, name: "Sandwich Restaurant" },
  { id: 147, name: "Agriculture and Forestry Service" },
  { id: 148, name: "Farm" },
  { id: 149, name: "Movie Theater" },
  { id: 150, name: "Steakhouse" },
  { id: 151, name: "Mexican Restaurant" },
  { id: 152, name: "Museum" },
  { id: 153, name: "Lake" },
  { id: 154, name: "Monument" },
  { id: 155, name: "Park" },
  { id: 156, name: "Dog Park" },
  { id: 157, name: "Plaza" },
  { id: 158, name: "Beach" },
  { id: 159, name: "Campground" },
  { id: 160, name: "Cocktail Bar" },
  { id: 161, name: "Coffee Shop" },
  { id: 162, name: "Soccer Field" },
  { id: 163, name: "Baseball Field" },
  { id: 164, name: "Golf Course" },
  { id: 165, name: "Skating Rink" },
  { id: 166, name: "Swimming Pool" },
  { id: 167, name: "Other Great Outdoors" },
  { id: 168, name: "State / Provincial Park" },
  { id: 169, name: "Concert Hall" },
  { id: 170, name: "Music Venue" },
  { id: 171, name: "Theater" },
  { id: 172, name: "Hiking Trail" },
  { id: 173, name: "Rock Climbing Spot" },
  { id: 174, name: "History Museum" },
  { id: 175, name: "Gym and Studio" },
  { id: 176, name: "Scenic Lookout" },
  { id: 177, name: "Ice Cream Parlor" },
  { id: 178, name: "Vineyard" },
  { id: 179, name: "Winery" },
  { id: 180, name: "Equestrian Facility" },
  { id: 181, name: "Memorial Site" },
  { id: 182, name: "Country Club" },
  { id: 183, name: "Picnic Area" },
  { id: 184, name: "Brewery" },
  { id: 185, name: "Café" },
  { id: 186, name: "Wine Bar" },
  { id: 187, name: "Salad Restaurant" },
  { id: 188, name: "Bar" },
  { id: 189, name: "Burger Joint" },
  { id: 190, name: "American Restaurant" },
  { id: 191, name: "Ski Resorts and Areas" },
  { id: 192, name: "National Park" },
  { id: 193, name: "Waterfall" },
  { id: 194, name: "Urban Park" },
  { id: 195, name: "River" },
  { id: 196, name: "Garden" },
  { id: 197, name: "Harbor / Marina" },
  { id: 198, name: "Lighthouse" },
  { id: 199, name: "Bike Trail" },
  { id: 200, name: "Bridge" },
  { id: 201, name: "Surf Spot" },
  { id: 202, name: "Deli" },
  { id: 203, name: "Arts and Entertainment" },
  { id: 204, name: "Distillery" },
  { id: 205, name: "Ski Lodge" },
  { id: 206, name: "Historic and Protected Site" },
  { id: 207, name: "Art Gallery" },
  { id: 208, name: "Botanical Garden" },
  { id: 209, name: "Natural Park" },
  { id: 210, name: "Nature Preserve" },
  { id: 211, name: "Science Museum" },
  { id: 212, name: "Mountain" },
  { id: 213, name: "Fast Food Restaurant" },
  { id: 214, name: "Building / Structure" },
  { id: 215, name: "Planetarium" },
  { id: 216, name: "Bowling Alley" },
  { id: 217, name: "Mini Golf Course" },
  { id: 218, name: "Water Park" },
  { id: 219, name: "Stadium" },
  { id: 220, name: "Amusement Park" },
  { id: 221, name: "Cave" },
  { id: 222, name: "RV Park" },
  { id: 223, name: "Arcade" },
  { id: 224, name: "Exhibit" },
  { id: 225, name: "Italian Restaurant" },
  { id: 226, name: "Reservoir" },
  { id: 227, name: "Seafood Restaurant" },
  { id: 228, name: "Swim School" },
  { id: 229, name: "Stable" },
  { id: 230, name: "Gastropub" },
  { id: 231, name: "Art Museum" },
  { id: 232, name: "Farmers' Market" },
  { id: 233, name: "Pizzeria" },
  { id: 234, name: "Education" },
  { id: 235, name: "Landmarks and Outdoors" },
  { id: 236, name: "Indie Movie Theater" },
  { id: 237, name: "Beer Bar" },
  { id: 238, name: "Cafes, Coffee, and Tea Houses" },
  { id: 239, name: "Cajun / Creole Restaurant" },
  { id: 240, name: "Night Club" },
  { id: 241, name: "Taco Restaurant" },
  { id: 242, name: "Sculpture Garden" },
  { id: 243, name: "Performing Arts Venue" },
  { id: 244, name: "Hotel Bar" },
  { id: 245, name: "Canoe and Kayak Rental" },
  { id: 246, name: "Forest" },
  { id: 247, name: "Dive Spot" },
  { id: 248, name: "Fair" },
  { id: 249, name: "South American Restaurant" },
  { id: 250, name: "Fruit and Vegetable Store" },
  { id: 251, name: "Organic Grocery" },
  { id: 252, name: "Mediterranean Restaurant" },
  { id: 253, name: "Caribbean Restaurant" },
  { id: 254, name: "BBQ Joint" },
  { id: 255, name: "Tapas Restaurant" },
  { id: 256, name: "Drive-in Theater" },
  { id: 257, name: "Beer Garden" },
  { id: 258, name: "Disc Golf Course" },
  { id: 259, name: "Asian Restaurant" },
  { id: 260, name: "Chinese Restaurant" },
  { id: 261, name: "Bagel Shop" },
  { id: 262, name: "Donut Shop" },
  { id: 263, name: "Southern / Soul Food Restaurant" },
  { id: 264, name: "Hawaiian Restaurant" },
  { id: 265, name: "Grocery Store / Supermarket" },
  { id: 266, name: "Recreation Center" },
  { id: 267, name: "Fountain" },
  { id: 268, name: "Ramen Restaurant" },
  { id: 269, name: "Cupcake Shop" },
  { id: 270, name: "Race Track" },
  { id: 271, name: "Sports Club" },
  { id: 272, name: "Rock Club" },
  { id: 273, name: "Public Art" },
  { id: 274, name: "Hot Dog Joint" },
  { id: 275, name: "Paintball Field" },
  { id: 276, name: "Sports Bar" },
  { id: 277, name: "Dessert Shop" },
  { id: 278, name: "Gourmet Store" },
  { id: 279, name: "Frozen Yogurt Shop" },
  { id: 280, name: "Belgian Restaurant" },
  { id: 281, name: "French Restaurant" },
  { id: 282, name: "Vegan and Vegetarian Restaurant" },
  { id: 283, name: "Food Truck" },
  { id: 284, name: "Business and Professional Services" },
  { id: 285, name: "Skate Park" },
  { id: 286, name: "Vacation Rental" },
  { id: 287, name: "Bistro" },
  { id: 288, name: "Candy Store" },
  { id: 289, name: "Outlet Store" },
  { id: 290, name: "Snow Sports" },
  { id: 291, name: "Veterinarian" },
  { id: 292, name: "Climbing Gym" },
  { id: 293, name: "Water Sports" },
  { id: 294, name: "Diner" },
  { id: 295, name: "Escape Room" },
  { id: 296, name: "Go Kart Track" },
  { id: 297, name: "Rafting Outfitter" },
  { id: 298, name: "Indoor Play Area" },
  { id: 299, name: "Cemetery" },
  { id: 300, name: "Sporting Goods Retail" },
  { id: 301, name: "Pet Supplies Store" },
  { id: 302, name: "Comfort Food Restaurant" },
  { id: 303, name: "Tennis Court" },
  { id: 304, name: "Jazz and Blues Venue" },
  { id: 305, name: "Cheese Store" },
  { id: 306, name: "Travel and Transportation" },
  { id: 307, name: "Hot Spring" },
  { id: 308, name: "Hotel" },
  { id: 309, name: "Spa" },
  { id: 310, name: "Opera House" },
  { id: 311, name: "Dive Bar" },
  { id: 312, name: "Lounge" },
  { id: 313, name: "Apres Ski Bar" },
  { id: 314, name: "Yoga Studio" },
  { id: 315, name: "Track" },
  { id: 316, name: "Hair Salon" },
  { id: 317, name: "Israeli Restaurant" },
  { id: 318, name: "Karaoke Bar" },
  { id: 319, name: "Australian Restaurant" },
  { id: 320, name: "Waterfront" },
  { id: 321, name: "Pedestrian Plaza" },
  { id: 322, name: "New American Restaurant" },
  { id: 323, name: "Comedy Club" },
  { id: 324, name: "Fried Chicken Joint" },
  { id: 325, name: "Drugstore" },
  { id: 326, name: "Hunting Supply Store" },
  { id: 327, name: "Meat and Seafood Store" },
  { id: 328, name: "Tea Room" },
  { id: 329, name: "Thai Restaurant" },
  { id: 330, name: "Hookah Bar" },
  { id: 331, name: "Middle Eastern Restaurant" },
  { id: 332, name: "Pub" },
  { id: 333, name: "Tex-Mex Restaurant" },
  { id: 334, name: "Shopping Mall" },
  { id: 335, name: "Sushi Restaurant" },
  { id: 336, name: "Latin American Restaurant" },
  { id: 337, name: "Bike Rental" },
  { id: 338, name: "Cuban Restaurant" },
  { id: 339, name: "Meadery" },
  { id: 351, name: "Moroccan Restaurant" },
  { id: 352, name: "Whisky Bar" },
  { id: 353, name: "Beer Store" },
  { id: 354, name: "Liquor Store" },
  { id: 355, name: "Buffet" },
  { id: 356, name: "Department Store" },
  { id: 357, name: "Noodle Restaurant" },
  { id: 358, name: "Breakfast Spot" },
  { id: 359, name: "Creperie" },
  { id: 360, name: "Golf Driving Range" },
  { id: 361, name: "Clothing Store" },
  { id: 362, name: "Men's Store" },
  { id: 363, name: "Vietnamese Restaurant" },
  { id: 364, name: "Garden Center" },
  { id: 365, name: "Health Food Store" },
  { id: 366, name: "Eastern European Restaurant" },
  { id: 367, name: "Hungarian Restaurant" },
  { id: 368, name: "Russian Restaurant" },
  { id: 370, name: "Roller & Hockey Rinks" },
  { id: 372, name: "Warehouse / Wholesale Store" },
  { id: 384, name: "Gathering" },
  { id: 385, name: "Meeting" },
  { id: 386, name: "Giveback Activity" }
];
